// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package cloudfront_test

import (
	"bytes"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/awserr"
	"github.com/aws/aws-sdk-go/aws/awsutil"
	"github.com/aws/aws-sdk-go/service/cloudfront"
)

var _ time.Duration
var _ bytes.Buffer

func ExampleCloudFront_CreateCloudFrontOriginAccessIdentity() {
	svc := cloudfront.New(nil)

	params := &cloudfront.CreateCloudFrontOriginAccessIdentityInput{
		CloudFrontOriginAccessIdentityConfig: &cloudfront.OriginAccessIdentityConfig{ // Required
			CallerReference: aws.StringPtr("string"), // Required
			Comment:         aws.StringPtr("string"), // Required
		},
	}
	resp, err := svc.CreateCloudFrontOriginAccessIdentity(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_CreateDistribution() {
	svc := cloudfront.New(nil)

	params := &cloudfront.CreateDistributionInput{
		DistributionConfig: &cloudfront.DistributionConfig{ // Required
			CallerReference: aws.StringPtr("string"), // Required
			Comment:         aws.StringPtr("string"), // Required
			DefaultCacheBehavior: &cloudfront.DefaultCacheBehavior{ // Required
				ForwardedValues: &cloudfront.ForwardedValues{ // Required
					Cookies: &cloudfront.CookiePreference{ // Required
						Forward: aws.StringPtr("ItemSelection"), // Required
						WhitelistedNames: &cloudfront.CookieNames{
							Quantity: aws.Int64Ptr(1), // Required
							Items: []*string{
								aws.StringPtr("string"), // Required
								// More values...
							},
						},
					},
					QueryString: aws.BoolPtr(true), // Required
					Headers: &cloudfront.Headers{
						Quantity: aws.Int64Ptr(1), // Required
						Items: []*string{
							aws.StringPtr("string"), // Required
							// More values...
						},
					},
				},
				MinTTL:         aws.Int64Ptr(1),         // Required
				TargetOriginID: aws.StringPtr("string"), // Required
				TrustedSigners: &cloudfront.TrustedSigners{ // Required
					Enabled:  aws.BoolPtr(true), // Required
					Quantity: aws.Int64Ptr(1),   // Required
					Items: []*string{
						aws.StringPtr("string"), // Required
						// More values...
					},
				},
				ViewerProtocolPolicy: aws.StringPtr("ViewerProtocolPolicy"), // Required
				AllowedMethods: &cloudfront.AllowedMethods{
					Items: []*string{ // Required
						aws.StringPtr("Method"), // Required
						// More values...
					},
					Quantity: aws.Int64Ptr(1), // Required
					CachedMethods: &cloudfront.CachedMethods{
						Items: []*string{ // Required
							aws.StringPtr("Method"), // Required
							// More values...
						},
						Quantity: aws.Int64Ptr(1), // Required
					},
				},
				DefaultTTL:      aws.Int64Ptr(1),
				MaxTTL:          aws.Int64Ptr(1),
				SmoothStreaming: aws.BoolPtr(true),
			},
			Enabled: aws.BoolPtr(true), // Required
			Origins: &cloudfront.Origins{ // Required
				Quantity: aws.Int64Ptr(1), // Required
				Items: []*cloudfront.Origin{
					{ // Required
						DomainName: aws.StringPtr("string"), // Required
						ID:         aws.StringPtr("string"), // Required
						CustomOriginConfig: &cloudfront.CustomOriginConfig{
							HTTPPort:             aws.Int64Ptr(1),                       // Required
							HTTPSPort:            aws.Int64Ptr(1),                       // Required
							OriginProtocolPolicy: aws.StringPtr("OriginProtocolPolicy"), // Required
						},
						OriginPath: aws.StringPtr("string"),
						S3OriginConfig: &cloudfront.S3OriginConfig{
							OriginAccessIdentity: aws.StringPtr("string"), // Required
						},
					},
					// More values...
				},
			},
			Aliases: &cloudfront.Aliases{
				Quantity: aws.Int64Ptr(1), // Required
				Items: []*string{
					aws.StringPtr("string"), // Required
					// More values...
				},
			},
			CacheBehaviors: &cloudfront.CacheBehaviors{
				Quantity: aws.Int64Ptr(1), // Required
				Items: []*cloudfront.CacheBehavior{
					{ // Required
						ForwardedValues: &cloudfront.ForwardedValues{ // Required
							Cookies: &cloudfront.CookiePreference{ // Required
								Forward: aws.StringPtr("ItemSelection"), // Required
								WhitelistedNames: &cloudfront.CookieNames{
									Quantity: aws.Int64Ptr(1), // Required
									Items: []*string{
										aws.StringPtr("string"), // Required
										// More values...
									},
								},
							},
							QueryString: aws.BoolPtr(true), // Required
							Headers: &cloudfront.Headers{
								Quantity: aws.Int64Ptr(1), // Required
								Items: []*string{
									aws.StringPtr("string"), // Required
									// More values...
								},
							},
						},
						MinTTL:         aws.Int64Ptr(1),         // Required
						PathPattern:    aws.StringPtr("string"), // Required
						TargetOriginID: aws.StringPtr("string"), // Required
						TrustedSigners: &cloudfront.TrustedSigners{ // Required
							Enabled:  aws.BoolPtr(true), // Required
							Quantity: aws.Int64Ptr(1),   // Required
							Items: []*string{
								aws.StringPtr("string"), // Required
								// More values...
							},
						},
						ViewerProtocolPolicy: aws.StringPtr("ViewerProtocolPolicy"), // Required
						AllowedMethods: &cloudfront.AllowedMethods{
							Items: []*string{ // Required
								aws.StringPtr("Method"), // Required
								// More values...
							},
							Quantity: aws.Int64Ptr(1), // Required
							CachedMethods: &cloudfront.CachedMethods{
								Items: []*string{ // Required
									aws.StringPtr("Method"), // Required
									// More values...
								},
								Quantity: aws.Int64Ptr(1), // Required
							},
						},
						DefaultTTL:      aws.Int64Ptr(1),
						MaxTTL:          aws.Int64Ptr(1),
						SmoothStreaming: aws.BoolPtr(true),
					},
					// More values...
				},
			},
			CustomErrorResponses: &cloudfront.CustomErrorResponses{
				Quantity: aws.Int64Ptr(1), // Required
				Items: []*cloudfront.CustomErrorResponse{
					{ // Required
						ErrorCode:          aws.Int64Ptr(1), // Required
						ErrorCachingMinTTL: aws.Int64Ptr(1),
						ResponseCode:       aws.StringPtr("string"),
						ResponsePagePath:   aws.StringPtr("string"),
					},
					// More values...
				},
			},
			DefaultRootObject: aws.StringPtr("string"),
			Logging: &cloudfront.LoggingConfig{
				Bucket:         aws.StringPtr("string"), // Required
				Enabled:        aws.BoolPtr(true),       // Required
				IncludeCookies: aws.BoolPtr(true),       // Required
				Prefix:         aws.StringPtr("string"), // Required
			},
			PriceClass: aws.StringPtr("PriceClass"),
			Restrictions: &cloudfront.Restrictions{
				GeoRestriction: &cloudfront.GeoRestriction{ // Required
					Quantity:        aws.Int64Ptr(1),                     // Required
					RestrictionType: aws.StringPtr("GeoRestrictionType"), // Required
					Items: []*string{
						aws.StringPtr("string"), // Required
						// More values...
					},
				},
			},
			ViewerCertificate: &cloudfront.ViewerCertificate{
				CloudFrontDefaultCertificate: aws.BoolPtr(true),
				IAMCertificateID:             aws.StringPtr("string"),
				MinimumProtocolVersion:       aws.StringPtr("MinimumProtocolVersion"),
				SSLSupportMethod:             aws.StringPtr("SSLSupportMethod"),
			},
		},
	}
	resp, err := svc.CreateDistribution(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_CreateInvalidation() {
	svc := cloudfront.New(nil)

	params := &cloudfront.CreateInvalidationInput{
		DistributionID: aws.StringPtr("string"), // Required
		InvalidationBatch: &cloudfront.InvalidationBatch{ // Required
			CallerReference: aws.StringPtr("string"), // Required
			Paths: &cloudfront.Paths{ // Required
				Quantity: aws.Int64Ptr(1), // Required
				Items: []*string{
					aws.StringPtr("string"), // Required
					// More values...
				},
			},
		},
	}
	resp, err := svc.CreateInvalidation(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_CreateStreamingDistribution() {
	svc := cloudfront.New(nil)

	params := &cloudfront.CreateStreamingDistributionInput{
		StreamingDistributionConfig: &cloudfront.StreamingDistributionConfig{ // Required
			CallerReference: aws.StringPtr("string"), // Required
			Comment:         aws.StringPtr("string"), // Required
			Enabled:         aws.BoolPtr(true),       // Required
			S3Origin: &cloudfront.S3Origin{ // Required
				DomainName:           aws.StringPtr("string"), // Required
				OriginAccessIdentity: aws.StringPtr("string"), // Required
			},
			TrustedSigners: &cloudfront.TrustedSigners{ // Required
				Enabled:  aws.BoolPtr(true), // Required
				Quantity: aws.Int64Ptr(1),   // Required
				Items: []*string{
					aws.StringPtr("string"), // Required
					// More values...
				},
			},
			Aliases: &cloudfront.Aliases{
				Quantity: aws.Int64Ptr(1), // Required
				Items: []*string{
					aws.StringPtr("string"), // Required
					// More values...
				},
			},
			Logging: &cloudfront.StreamingLoggingConfig{
				Bucket:  aws.StringPtr("string"), // Required
				Enabled: aws.BoolPtr(true),       // Required
				Prefix:  aws.StringPtr("string"), // Required
			},
			PriceClass: aws.StringPtr("PriceClass"),
		},
	}
	resp, err := svc.CreateStreamingDistribution(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_DeleteCloudFrontOriginAccessIdentity() {
	svc := cloudfront.New(nil)

	params := &cloudfront.DeleteCloudFrontOriginAccessIdentityInput{
		ID:      aws.StringPtr("string"), // Required
		IfMatch: aws.StringPtr("string"),
	}
	resp, err := svc.DeleteCloudFrontOriginAccessIdentity(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_DeleteDistribution() {
	svc := cloudfront.New(nil)

	params := &cloudfront.DeleteDistributionInput{
		ID:      aws.StringPtr("string"), // Required
		IfMatch: aws.StringPtr("string"),
	}
	resp, err := svc.DeleteDistribution(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_DeleteStreamingDistribution() {
	svc := cloudfront.New(nil)

	params := &cloudfront.DeleteStreamingDistributionInput{
		ID:      aws.StringPtr("string"), // Required
		IfMatch: aws.StringPtr("string"),
	}
	resp, err := svc.DeleteStreamingDistribution(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_GetCloudFrontOriginAccessIdentity() {
	svc := cloudfront.New(nil)

	params := &cloudfront.GetCloudFrontOriginAccessIdentityInput{
		ID: aws.StringPtr("string"), // Required
	}
	resp, err := svc.GetCloudFrontOriginAccessIdentity(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_GetCloudFrontOriginAccessIdentityConfig() {
	svc := cloudfront.New(nil)

	params := &cloudfront.GetCloudFrontOriginAccessIdentityConfigInput{
		ID: aws.StringPtr("string"), // Required
	}
	resp, err := svc.GetCloudFrontOriginAccessIdentityConfig(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_GetDistribution() {
	svc := cloudfront.New(nil)

	params := &cloudfront.GetDistributionInput{
		ID: aws.StringPtr("string"), // Required
	}
	resp, err := svc.GetDistribution(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_GetDistributionConfig() {
	svc := cloudfront.New(nil)

	params := &cloudfront.GetDistributionConfigInput{
		ID: aws.StringPtr("string"), // Required
	}
	resp, err := svc.GetDistributionConfig(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_GetInvalidation() {
	svc := cloudfront.New(nil)

	params := &cloudfront.GetInvalidationInput{
		DistributionID: aws.StringPtr("string"), // Required
		ID:             aws.StringPtr("string"), // Required
	}
	resp, err := svc.GetInvalidation(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_GetStreamingDistribution() {
	svc := cloudfront.New(nil)

	params := &cloudfront.GetStreamingDistributionInput{
		ID: aws.StringPtr("string"), // Required
	}
	resp, err := svc.GetStreamingDistribution(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_GetStreamingDistributionConfig() {
	svc := cloudfront.New(nil)

	params := &cloudfront.GetStreamingDistributionConfigInput{
		ID: aws.StringPtr("string"), // Required
	}
	resp, err := svc.GetStreamingDistributionConfig(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_ListCloudFrontOriginAccessIdentities() {
	svc := cloudfront.New(nil)

	params := &cloudfront.ListCloudFrontOriginAccessIdentitiesInput{
		Marker:   aws.StringPtr("string"),
		MaxItems: aws.Int64Ptr(1),
	}
	resp, err := svc.ListCloudFrontOriginAccessIdentities(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_ListDistributions() {
	svc := cloudfront.New(nil)

	params := &cloudfront.ListDistributionsInput{
		Marker:   aws.StringPtr("string"),
		MaxItems: aws.Int64Ptr(1),
	}
	resp, err := svc.ListDistributions(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_ListInvalidations() {
	svc := cloudfront.New(nil)

	params := &cloudfront.ListInvalidationsInput{
		DistributionID: aws.StringPtr("string"), // Required
		Marker:         aws.StringPtr("string"),
		MaxItems:       aws.Int64Ptr(1),
	}
	resp, err := svc.ListInvalidations(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_ListStreamingDistributions() {
	svc := cloudfront.New(nil)

	params := &cloudfront.ListStreamingDistributionsInput{
		Marker:   aws.StringPtr("string"),
		MaxItems: aws.Int64Ptr(1),
	}
	resp, err := svc.ListStreamingDistributions(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_UpdateCloudFrontOriginAccessIdentity() {
	svc := cloudfront.New(nil)

	params := &cloudfront.UpdateCloudFrontOriginAccessIdentityInput{
		CloudFrontOriginAccessIdentityConfig: &cloudfront.OriginAccessIdentityConfig{ // Required
			CallerReference: aws.StringPtr("string"), // Required
			Comment:         aws.StringPtr("string"), // Required
		},
		ID:      aws.StringPtr("string"), // Required
		IfMatch: aws.StringPtr("string"),
	}
	resp, err := svc.UpdateCloudFrontOriginAccessIdentity(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_UpdateDistribution() {
	svc := cloudfront.New(nil)

	params := &cloudfront.UpdateDistributionInput{
		DistributionConfig: &cloudfront.DistributionConfig{ // Required
			CallerReference: aws.StringPtr("string"), // Required
			Comment:         aws.StringPtr("string"), // Required
			DefaultCacheBehavior: &cloudfront.DefaultCacheBehavior{ // Required
				ForwardedValues: &cloudfront.ForwardedValues{ // Required
					Cookies: &cloudfront.CookiePreference{ // Required
						Forward: aws.StringPtr("ItemSelection"), // Required
						WhitelistedNames: &cloudfront.CookieNames{
							Quantity: aws.Int64Ptr(1), // Required
							Items: []*string{
								aws.StringPtr("string"), // Required
								// More values...
							},
						},
					},
					QueryString: aws.BoolPtr(true), // Required
					Headers: &cloudfront.Headers{
						Quantity: aws.Int64Ptr(1), // Required
						Items: []*string{
							aws.StringPtr("string"), // Required
							// More values...
						},
					},
				},
				MinTTL:         aws.Int64Ptr(1),         // Required
				TargetOriginID: aws.StringPtr("string"), // Required
				TrustedSigners: &cloudfront.TrustedSigners{ // Required
					Enabled:  aws.BoolPtr(true), // Required
					Quantity: aws.Int64Ptr(1),   // Required
					Items: []*string{
						aws.StringPtr("string"), // Required
						// More values...
					},
				},
				ViewerProtocolPolicy: aws.StringPtr("ViewerProtocolPolicy"), // Required
				AllowedMethods: &cloudfront.AllowedMethods{
					Items: []*string{ // Required
						aws.StringPtr("Method"), // Required
						// More values...
					},
					Quantity: aws.Int64Ptr(1), // Required
					CachedMethods: &cloudfront.CachedMethods{
						Items: []*string{ // Required
							aws.StringPtr("Method"), // Required
							// More values...
						},
						Quantity: aws.Int64Ptr(1), // Required
					},
				},
				DefaultTTL:      aws.Int64Ptr(1),
				MaxTTL:          aws.Int64Ptr(1),
				SmoothStreaming: aws.BoolPtr(true),
			},
			Enabled: aws.BoolPtr(true), // Required
			Origins: &cloudfront.Origins{ // Required
				Quantity: aws.Int64Ptr(1), // Required
				Items: []*cloudfront.Origin{
					{ // Required
						DomainName: aws.StringPtr("string"), // Required
						ID:         aws.StringPtr("string"), // Required
						CustomOriginConfig: &cloudfront.CustomOriginConfig{
							HTTPPort:             aws.Int64Ptr(1),                       // Required
							HTTPSPort:            aws.Int64Ptr(1),                       // Required
							OriginProtocolPolicy: aws.StringPtr("OriginProtocolPolicy"), // Required
						},
						OriginPath: aws.StringPtr("string"),
						S3OriginConfig: &cloudfront.S3OriginConfig{
							OriginAccessIdentity: aws.StringPtr("string"), // Required
						},
					},
					// More values...
				},
			},
			Aliases: &cloudfront.Aliases{
				Quantity: aws.Int64Ptr(1), // Required
				Items: []*string{
					aws.StringPtr("string"), // Required
					// More values...
				},
			},
			CacheBehaviors: &cloudfront.CacheBehaviors{
				Quantity: aws.Int64Ptr(1), // Required
				Items: []*cloudfront.CacheBehavior{
					{ // Required
						ForwardedValues: &cloudfront.ForwardedValues{ // Required
							Cookies: &cloudfront.CookiePreference{ // Required
								Forward: aws.StringPtr("ItemSelection"), // Required
								WhitelistedNames: &cloudfront.CookieNames{
									Quantity: aws.Int64Ptr(1), // Required
									Items: []*string{
										aws.StringPtr("string"), // Required
										// More values...
									},
								},
							},
							QueryString: aws.BoolPtr(true), // Required
							Headers: &cloudfront.Headers{
								Quantity: aws.Int64Ptr(1), // Required
								Items: []*string{
									aws.StringPtr("string"), // Required
									// More values...
								},
							},
						},
						MinTTL:         aws.Int64Ptr(1),         // Required
						PathPattern:    aws.StringPtr("string"), // Required
						TargetOriginID: aws.StringPtr("string"), // Required
						TrustedSigners: &cloudfront.TrustedSigners{ // Required
							Enabled:  aws.BoolPtr(true), // Required
							Quantity: aws.Int64Ptr(1),   // Required
							Items: []*string{
								aws.StringPtr("string"), // Required
								// More values...
							},
						},
						ViewerProtocolPolicy: aws.StringPtr("ViewerProtocolPolicy"), // Required
						AllowedMethods: &cloudfront.AllowedMethods{
							Items: []*string{ // Required
								aws.StringPtr("Method"), // Required
								// More values...
							},
							Quantity: aws.Int64Ptr(1), // Required
							CachedMethods: &cloudfront.CachedMethods{
								Items: []*string{ // Required
									aws.StringPtr("Method"), // Required
									// More values...
								},
								Quantity: aws.Int64Ptr(1), // Required
							},
						},
						DefaultTTL:      aws.Int64Ptr(1),
						MaxTTL:          aws.Int64Ptr(1),
						SmoothStreaming: aws.BoolPtr(true),
					},
					// More values...
				},
			},
			CustomErrorResponses: &cloudfront.CustomErrorResponses{
				Quantity: aws.Int64Ptr(1), // Required
				Items: []*cloudfront.CustomErrorResponse{
					{ // Required
						ErrorCode:          aws.Int64Ptr(1), // Required
						ErrorCachingMinTTL: aws.Int64Ptr(1),
						ResponseCode:       aws.StringPtr("string"),
						ResponsePagePath:   aws.StringPtr("string"),
					},
					// More values...
				},
			},
			DefaultRootObject: aws.StringPtr("string"),
			Logging: &cloudfront.LoggingConfig{
				Bucket:         aws.StringPtr("string"), // Required
				Enabled:        aws.BoolPtr(true),       // Required
				IncludeCookies: aws.BoolPtr(true),       // Required
				Prefix:         aws.StringPtr("string"), // Required
			},
			PriceClass: aws.StringPtr("PriceClass"),
			Restrictions: &cloudfront.Restrictions{
				GeoRestriction: &cloudfront.GeoRestriction{ // Required
					Quantity:        aws.Int64Ptr(1),                     // Required
					RestrictionType: aws.StringPtr("GeoRestrictionType"), // Required
					Items: []*string{
						aws.StringPtr("string"), // Required
						// More values...
					},
				},
			},
			ViewerCertificate: &cloudfront.ViewerCertificate{
				CloudFrontDefaultCertificate: aws.BoolPtr(true),
				IAMCertificateID:             aws.StringPtr("string"),
				MinimumProtocolVersion:       aws.StringPtr("MinimumProtocolVersion"),
				SSLSupportMethod:             aws.StringPtr("SSLSupportMethod"),
			},
		},
		ID:      aws.StringPtr("string"), // Required
		IfMatch: aws.StringPtr("string"),
	}
	resp, err := svc.UpdateDistribution(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleCloudFront_UpdateStreamingDistribution() {
	svc := cloudfront.New(nil)

	params := &cloudfront.UpdateStreamingDistributionInput{
		ID: aws.StringPtr("string"), // Required
		StreamingDistributionConfig: &cloudfront.StreamingDistributionConfig{ // Required
			CallerReference: aws.StringPtr("string"), // Required
			Comment:         aws.StringPtr("string"), // Required
			Enabled:         aws.BoolPtr(true),       // Required
			S3Origin: &cloudfront.S3Origin{ // Required
				DomainName:           aws.StringPtr("string"), // Required
				OriginAccessIdentity: aws.StringPtr("string"), // Required
			},
			TrustedSigners: &cloudfront.TrustedSigners{ // Required
				Enabled:  aws.BoolPtr(true), // Required
				Quantity: aws.Int64Ptr(1),   // Required
				Items: []*string{
					aws.StringPtr("string"), // Required
					// More values...
				},
			},
			Aliases: &cloudfront.Aliases{
				Quantity: aws.Int64Ptr(1), // Required
				Items: []*string{
					aws.StringPtr("string"), // Required
					// More values...
				},
			},
			Logging: &cloudfront.StreamingLoggingConfig{
				Bucket:  aws.StringPtr("string"), // Required
				Enabled: aws.BoolPtr(true),       // Required
				Prefix:  aws.StringPtr("string"), // Required
			},
			PriceClass: aws.StringPtr("PriceClass"),
		},
		IfMatch: aws.StringPtr("string"),
	}
	resp, err := svc.UpdateStreamingDistribution(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}
