// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package route53domains_test

import (
	"bytes"
	"fmt"
	"time"

	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/awserr"
	"github.com/aws/aws-sdk-go/aws/awsutil"
	"github.com/aws/aws-sdk-go/service/route53domains"
)

var _ time.Duration
var _ bytes.Buffer

func ExampleRoute53Domains_CheckDomainAvailability() {
	svc := route53domains.New(nil)

	params := &route53domains.CheckDomainAvailabilityInput{
		DomainName:  aws.StringPtr("DomainName"), // Required
		IDNLangCode: aws.StringPtr("LangCode"),
	}
	resp, err := svc.CheckDomainAvailability(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_DeleteTagsForDomain() {
	svc := route53domains.New(nil)

	params := &route53domains.DeleteTagsForDomainInput{
		DomainName: aws.StringPtr("DomainName"), // Required
		TagsToDelete: []*string{ // Required
			aws.StringPtr("TagKey"), // Required
			// More values...
		},
	}
	resp, err := svc.DeleteTagsForDomain(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_DisableDomainAutoRenew() {
	svc := route53domains.New(nil)

	params := &route53domains.DisableDomainAutoRenewInput{
		DomainName: aws.StringPtr("DomainName"), // Required
	}
	resp, err := svc.DisableDomainAutoRenew(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_DisableDomainTransferLock() {
	svc := route53domains.New(nil)

	params := &route53domains.DisableDomainTransferLockInput{
		DomainName: aws.StringPtr("DomainName"), // Required
	}
	resp, err := svc.DisableDomainTransferLock(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_EnableDomainAutoRenew() {
	svc := route53domains.New(nil)

	params := &route53domains.EnableDomainAutoRenewInput{
		DomainName: aws.StringPtr("DomainName"), // Required
	}
	resp, err := svc.EnableDomainAutoRenew(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_EnableDomainTransferLock() {
	svc := route53domains.New(nil)

	params := &route53domains.EnableDomainTransferLockInput{
		DomainName: aws.StringPtr("DomainName"), // Required
	}
	resp, err := svc.EnableDomainTransferLock(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_GetDomainDetail() {
	svc := route53domains.New(nil)

	params := &route53domains.GetDomainDetailInput{
		DomainName: aws.StringPtr("DomainName"), // Required
	}
	resp, err := svc.GetDomainDetail(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_GetOperationDetail() {
	svc := route53domains.New(nil)

	params := &route53domains.GetOperationDetailInput{
		OperationID: aws.StringPtr("OperationId"), // Required
	}
	resp, err := svc.GetOperationDetail(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_ListDomains() {
	svc := route53domains.New(nil)

	params := &route53domains.ListDomainsInput{
		Marker:   aws.StringPtr("PageMarker"),
		MaxItems: aws.Int64Ptr(1),
	}
	resp, err := svc.ListDomains(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_ListOperations() {
	svc := route53domains.New(nil)

	params := &route53domains.ListOperationsInput{
		Marker:   aws.StringPtr("PageMarker"),
		MaxItems: aws.Int64Ptr(1),
	}
	resp, err := svc.ListOperations(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_ListTagsForDomain() {
	svc := route53domains.New(nil)

	params := &route53domains.ListTagsForDomainInput{
		DomainName: aws.StringPtr("DomainName"), // Required
	}
	resp, err := svc.ListTagsForDomain(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_RegisterDomain() {
	svc := route53domains.New(nil)

	params := &route53domains.RegisterDomainInput{
		AdminContact: &route53domains.ContactDetail{ // Required
			AddressLine1: aws.StringPtr("AddressLine"),
			AddressLine2: aws.StringPtr("AddressLine"),
			City:         aws.StringPtr("City"),
			ContactType:  aws.StringPtr("ContactType"),
			CountryCode:  aws.StringPtr("CountryCode"),
			Email:        aws.StringPtr("Email"),
			ExtraParams: []*route53domains.ExtraParam{
				{ // Required
					Name:  aws.StringPtr("ExtraParamName"),  // Required
					Value: aws.StringPtr("ExtraParamValue"), // Required
				},
				// More values...
			},
			Fax:              aws.StringPtr("ContactNumber"),
			FirstName:        aws.StringPtr("ContactName"),
			LastName:         aws.StringPtr("ContactName"),
			OrganizationName: aws.StringPtr("ContactName"),
			PhoneNumber:      aws.StringPtr("ContactNumber"),
			State:            aws.StringPtr("State"),
			ZipCode:          aws.StringPtr("ZipCode"),
		},
		DomainName:      aws.StringPtr("DomainName"), // Required
		DurationInYears: aws.Int64Ptr(1),             // Required
		RegistrantContact: &route53domains.ContactDetail{ // Required
			AddressLine1: aws.StringPtr("AddressLine"),
			AddressLine2: aws.StringPtr("AddressLine"),
			City:         aws.StringPtr("City"),
			ContactType:  aws.StringPtr("ContactType"),
			CountryCode:  aws.StringPtr("CountryCode"),
			Email:        aws.StringPtr("Email"),
			ExtraParams: []*route53domains.ExtraParam{
				{ // Required
					Name:  aws.StringPtr("ExtraParamName"),  // Required
					Value: aws.StringPtr("ExtraParamValue"), // Required
				},
				// More values...
			},
			Fax:              aws.StringPtr("ContactNumber"),
			FirstName:        aws.StringPtr("ContactName"),
			LastName:         aws.StringPtr("ContactName"),
			OrganizationName: aws.StringPtr("ContactName"),
			PhoneNumber:      aws.StringPtr("ContactNumber"),
			State:            aws.StringPtr("State"),
			ZipCode:          aws.StringPtr("ZipCode"),
		},
		TechContact: &route53domains.ContactDetail{ // Required
			AddressLine1: aws.StringPtr("AddressLine"),
			AddressLine2: aws.StringPtr("AddressLine"),
			City:         aws.StringPtr("City"),
			ContactType:  aws.StringPtr("ContactType"),
			CountryCode:  aws.StringPtr("CountryCode"),
			Email:        aws.StringPtr("Email"),
			ExtraParams: []*route53domains.ExtraParam{
				{ // Required
					Name:  aws.StringPtr("ExtraParamName"),  // Required
					Value: aws.StringPtr("ExtraParamValue"), // Required
				},
				// More values...
			},
			Fax:              aws.StringPtr("ContactNumber"),
			FirstName:        aws.StringPtr("ContactName"),
			LastName:         aws.StringPtr("ContactName"),
			OrganizationName: aws.StringPtr("ContactName"),
			PhoneNumber:      aws.StringPtr("ContactNumber"),
			State:            aws.StringPtr("State"),
			ZipCode:          aws.StringPtr("ZipCode"),
		},
		AutoRenew:                       aws.BoolPtr(true),
		IDNLangCode:                     aws.StringPtr("LangCode"),
		PrivacyProtectAdminContact:      aws.BoolPtr(true),
		PrivacyProtectRegistrantContact: aws.BoolPtr(true),
		PrivacyProtectTechContact:       aws.BoolPtr(true),
	}
	resp, err := svc.RegisterDomain(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_RetrieveDomainAuthCode() {
	svc := route53domains.New(nil)

	params := &route53domains.RetrieveDomainAuthCodeInput{
		DomainName: aws.StringPtr("DomainName"), // Required
	}
	resp, err := svc.RetrieveDomainAuthCode(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_TransferDomain() {
	svc := route53domains.New(nil)

	params := &route53domains.TransferDomainInput{
		AdminContact: &route53domains.ContactDetail{ // Required
			AddressLine1: aws.StringPtr("AddressLine"),
			AddressLine2: aws.StringPtr("AddressLine"),
			City:         aws.StringPtr("City"),
			ContactType:  aws.StringPtr("ContactType"),
			CountryCode:  aws.StringPtr("CountryCode"),
			Email:        aws.StringPtr("Email"),
			ExtraParams: []*route53domains.ExtraParam{
				{ // Required
					Name:  aws.StringPtr("ExtraParamName"),  // Required
					Value: aws.StringPtr("ExtraParamValue"), // Required
				},
				// More values...
			},
			Fax:              aws.StringPtr("ContactNumber"),
			FirstName:        aws.StringPtr("ContactName"),
			LastName:         aws.StringPtr("ContactName"),
			OrganizationName: aws.StringPtr("ContactName"),
			PhoneNumber:      aws.StringPtr("ContactNumber"),
			State:            aws.StringPtr("State"),
			ZipCode:          aws.StringPtr("ZipCode"),
		},
		DomainName:      aws.StringPtr("DomainName"), // Required
		DurationInYears: aws.Int64Ptr(1),             // Required
		RegistrantContact: &route53domains.ContactDetail{ // Required
			AddressLine1: aws.StringPtr("AddressLine"),
			AddressLine2: aws.StringPtr("AddressLine"),
			City:         aws.StringPtr("City"),
			ContactType:  aws.StringPtr("ContactType"),
			CountryCode:  aws.StringPtr("CountryCode"),
			Email:        aws.StringPtr("Email"),
			ExtraParams: []*route53domains.ExtraParam{
				{ // Required
					Name:  aws.StringPtr("ExtraParamName"),  // Required
					Value: aws.StringPtr("ExtraParamValue"), // Required
				},
				// More values...
			},
			Fax:              aws.StringPtr("ContactNumber"),
			FirstName:        aws.StringPtr("ContactName"),
			LastName:         aws.StringPtr("ContactName"),
			OrganizationName: aws.StringPtr("ContactName"),
			PhoneNumber:      aws.StringPtr("ContactNumber"),
			State:            aws.StringPtr("State"),
			ZipCode:          aws.StringPtr("ZipCode"),
		},
		TechContact: &route53domains.ContactDetail{ // Required
			AddressLine1: aws.StringPtr("AddressLine"),
			AddressLine2: aws.StringPtr("AddressLine"),
			City:         aws.StringPtr("City"),
			ContactType:  aws.StringPtr("ContactType"),
			CountryCode:  aws.StringPtr("CountryCode"),
			Email:        aws.StringPtr("Email"),
			ExtraParams: []*route53domains.ExtraParam{
				{ // Required
					Name:  aws.StringPtr("ExtraParamName"),  // Required
					Value: aws.StringPtr("ExtraParamValue"), // Required
				},
				// More values...
			},
			Fax:              aws.StringPtr("ContactNumber"),
			FirstName:        aws.StringPtr("ContactName"),
			LastName:         aws.StringPtr("ContactName"),
			OrganizationName: aws.StringPtr("ContactName"),
			PhoneNumber:      aws.StringPtr("ContactNumber"),
			State:            aws.StringPtr("State"),
			ZipCode:          aws.StringPtr("ZipCode"),
		},
		AuthCode:    aws.StringPtr("DomainAuthCode"),
		AutoRenew:   aws.BoolPtr(true),
		IDNLangCode: aws.StringPtr("LangCode"),
		Nameservers: []*route53domains.Nameserver{
			{ // Required
				Name: aws.StringPtr("HostName"), // Required
				GlueIPs: []*string{
					aws.StringPtr("GlueIp"), // Required
					// More values...
				},
			},
			// More values...
		},
		PrivacyProtectAdminContact:      aws.BoolPtr(true),
		PrivacyProtectRegistrantContact: aws.BoolPtr(true),
		PrivacyProtectTechContact:       aws.BoolPtr(true),
	}
	resp, err := svc.TransferDomain(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_UpdateDomainContact() {
	svc := route53domains.New(nil)

	params := &route53domains.UpdateDomainContactInput{
		DomainName: aws.StringPtr("DomainName"), // Required
		AdminContact: &route53domains.ContactDetail{
			AddressLine1: aws.StringPtr("AddressLine"),
			AddressLine2: aws.StringPtr("AddressLine"),
			City:         aws.StringPtr("City"),
			ContactType:  aws.StringPtr("ContactType"),
			CountryCode:  aws.StringPtr("CountryCode"),
			Email:        aws.StringPtr("Email"),
			ExtraParams: []*route53domains.ExtraParam{
				{ // Required
					Name:  aws.StringPtr("ExtraParamName"),  // Required
					Value: aws.StringPtr("ExtraParamValue"), // Required
				},
				// More values...
			},
			Fax:              aws.StringPtr("ContactNumber"),
			FirstName:        aws.StringPtr("ContactName"),
			LastName:         aws.StringPtr("ContactName"),
			OrganizationName: aws.StringPtr("ContactName"),
			PhoneNumber:      aws.StringPtr("ContactNumber"),
			State:            aws.StringPtr("State"),
			ZipCode:          aws.StringPtr("ZipCode"),
		},
		RegistrantContact: &route53domains.ContactDetail{
			AddressLine1: aws.StringPtr("AddressLine"),
			AddressLine2: aws.StringPtr("AddressLine"),
			City:         aws.StringPtr("City"),
			ContactType:  aws.StringPtr("ContactType"),
			CountryCode:  aws.StringPtr("CountryCode"),
			Email:        aws.StringPtr("Email"),
			ExtraParams: []*route53domains.ExtraParam{
				{ // Required
					Name:  aws.StringPtr("ExtraParamName"),  // Required
					Value: aws.StringPtr("ExtraParamValue"), // Required
				},
				// More values...
			},
			Fax:              aws.StringPtr("ContactNumber"),
			FirstName:        aws.StringPtr("ContactName"),
			LastName:         aws.StringPtr("ContactName"),
			OrganizationName: aws.StringPtr("ContactName"),
			PhoneNumber:      aws.StringPtr("ContactNumber"),
			State:            aws.StringPtr("State"),
			ZipCode:          aws.StringPtr("ZipCode"),
		},
		TechContact: &route53domains.ContactDetail{
			AddressLine1: aws.StringPtr("AddressLine"),
			AddressLine2: aws.StringPtr("AddressLine"),
			City:         aws.StringPtr("City"),
			ContactType:  aws.StringPtr("ContactType"),
			CountryCode:  aws.StringPtr("CountryCode"),
			Email:        aws.StringPtr("Email"),
			ExtraParams: []*route53domains.ExtraParam{
				{ // Required
					Name:  aws.StringPtr("ExtraParamName"),  // Required
					Value: aws.StringPtr("ExtraParamValue"), // Required
				},
				// More values...
			},
			Fax:              aws.StringPtr("ContactNumber"),
			FirstName:        aws.StringPtr("ContactName"),
			LastName:         aws.StringPtr("ContactName"),
			OrganizationName: aws.StringPtr("ContactName"),
			PhoneNumber:      aws.StringPtr("ContactNumber"),
			State:            aws.StringPtr("State"),
			ZipCode:          aws.StringPtr("ZipCode"),
		},
	}
	resp, err := svc.UpdateDomainContact(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_UpdateDomainContactPrivacy() {
	svc := route53domains.New(nil)

	params := &route53domains.UpdateDomainContactPrivacyInput{
		DomainName:        aws.StringPtr("DomainName"), // Required
		AdminPrivacy:      aws.BoolPtr(true),
		RegistrantPrivacy: aws.BoolPtr(true),
		TechPrivacy:       aws.BoolPtr(true),
	}
	resp, err := svc.UpdateDomainContactPrivacy(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_UpdateDomainNameservers() {
	svc := route53domains.New(nil)

	params := &route53domains.UpdateDomainNameserversInput{
		DomainName: aws.StringPtr("DomainName"), // Required
		Nameservers: []*route53domains.Nameserver{ // Required
			{ // Required
				Name: aws.StringPtr("HostName"), // Required
				GlueIPs: []*string{
					aws.StringPtr("GlueIp"), // Required
					// More values...
				},
			},
			// More values...
		},
		FIAuthKey: aws.StringPtr("FIAuthKey"),
	}
	resp, err := svc.UpdateDomainNameservers(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}

func ExampleRoute53Domains_UpdateTagsForDomain() {
	svc := route53domains.New(nil)

	params := &route53domains.UpdateTagsForDomainInput{
		DomainName: aws.StringPtr("DomainName"), // Required
		TagsToUpdate: []*route53domains.Tag{
			{ // Required
				Key:   aws.StringPtr("TagKey"),
				Value: aws.StringPtr("TagValue"),
			},
			// More values...
		},
	}
	resp, err := svc.UpdateTagsForDomain(params)

	if err != nil {
		if awsErr, ok := err.(awserr.Error); ok {
			// Generic AWS Error with Code, Message, and original error (if any)
			fmt.Println(awsErr.Code(), awsErr.Message(), awsErr.OrigErr())
			if reqErr, ok := err.(awserr.RequestFailure); ok {
				// A service error occurred
				fmt.Println(reqErr.Code(), reqErr.Message(), reqErr.StatusCode(), reqErr.RequestID())
			}
		} else {
			// This case should never be hit, the SDK should always return an
			// error which satisfies the awserr.Error interface.
			fmt.Println(err.Error())
		}
	}

	// Pretty-print the response data.
	fmt.Println(awsutil.StringValue(resp))
}
